import { FaRobot, FaLightbulb } from "react-icons/fa";
import { motion } from "framer-motion";

const AIInsightsCard = ({ insights }) => {

    const formattedInsights = () => {

    if (!insights)
        return [];

    // Array response
    if (Array.isArray(insights))
        return insights;


    // String response
    if (typeof insights === "string") {

        return insights
            .split("\n")
            .map(line => line.replace(/^\*\s*/, "").trim())
            .filter(Boolean);

    }


    // Object response
    if (typeof insights === "object") {

        if (Array.isArray(insights.insights)) {

            return insights.insights;

        }

        if (typeof insights.insights === "string") {

            return insights.insights
                .split("\n")
                .map(line => line.replace(/^\*\s*/, "").trim())
                .filter(Boolean);

        }

    }


    return [];

};

    const data = formattedInsights();

    return (

        <motion.div

            whileHover={{
                y: -5
            }}

            className="bg-white rounded-3xl border border-gray-100 shadow-sm p-6 h-full"

        >

            <div className="flex items-center gap-3 mb-6">

                <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">

                    <FaRobot
                        className="text-blue-600 text-xl"
                    />

                </div>

                <div>

                    <h2 className="text-xl font-semibold">

                        AI Insights

                    </h2>

                    <p className="text-gray-500 text-sm">

                        Generated by Gemini AI

                    </p>

                </div>

            </div>

            {

                data.length === 0 ?

                (

                    <div className="h-64 flex items-center justify-center text-gray-400">

                        No insights generated.

                    </div>

                )

                :

                (

                    <div className="space-y-4">

                        {

                            data.map((item,index)=>(

                                <div

                                    key={index}

                                    className="flex gap-4 p-4 rounded-2xl bg-blue-50"

                                >

                                    <FaLightbulb

                                        className="text-blue-600 mt-1"

                                    />

                                    <p

                                        className="text-gray-700 leading-7"

                                    >

                                        {item}

                                    </p>

                                </div>

                            ))

                        }

                    </div>

                )

            }

        </motion.div>

    );

};

export default AIInsightsCard;